#!/usr/bin/env python

# Derived from https://github.com/jackal/jackal_robot/tree/melodic-devel/jackal_bringup
# Modified by Greg Baker (BRL)
# Brief: Add base.launch to startup services as "p3at_base"
# 
# Known Issues:
# - Raspberry pi /etc/udev/rules.d/99-com.rules was setting permissions for i2c and inputs to "0660",
#   which prevents 'other' users from running these interfaces, which impacted joystick & imu.
#   robot_upstart docs suggests that the user should be the same as the one who ran the install script,
#   so I am unsure why this was blocking these interfaces on startup, because the user has perm's for both.

import os
import robot_upstart


j = robot_upstart.Job(workspace_setup=os.environ['ROBOT_SETUP'])
j.add(package="p3at_base", filename="launch/base.launch")
j.add(package="p3at_bringup", filename="launch/accessories.launch")
j.install()
