#Configuation for robot odometry EKF
#
two_d_mode: true
frequency: 50

odom0: /p3at_velocity_controller/odom
odom0_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: false

imu0: /imu/data
imu0_config: [false, false, false,
              false, false, false,
              false, false, false,
              true, true, true,
              true, false, false]
imu0_differential: false

odom_frame: odom
base_link_frame: base_link
world_frame: odom
